# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestUI01.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1184, 853)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 20, 967, 751))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelView = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelView.setObjectName("labelView")
        self.verticalLayout.addWidget(self.labelView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonw = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButtonw.setFont(font)
        self.pushButtonw.setObjectName("pushButtonw")
        self.gridLayout_2.addWidget(self.pushButtonw, 0, 1, 1, 1)
        self.pushButton_stop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout_2.addWidget(self.pushButton_stop, 1, 1, 1, 1)
        self.pushButtona = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButtona.setFont(font)
        self.pushButtona.setObjectName("pushButtona")
        self.gridLayout_2.addWidget(self.pushButtona, 1, 0, 1, 1)
        self.pushButtons = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButtons.setFont(font)
        self.pushButtons.setObjectName("pushButtons")
        self.gridLayout_2.addWidget(self.pushButtons, 2, 1, 1, 1)
        self.pushButtond = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButtond.setFont(font)
        self.pushButtond.setObjectName("pushButtond")
        self.gridLayout_2.addWidget(self.pushButtond, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinBox_speed = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.spinBox_speed.setFont(font)
        self.spinBox_speed.setMinimum(10)
        self.spinBox_speed.setMaximum(50)
        self.spinBox_speed.setSingleStep(5)
        self.spinBox_speed.setProperty("value", 30)
        self.spinBox_speed.setObjectName("spinBox_speed")
        self.horizontalLayout_2.addWidget(self.spinBox_speed)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.pushButton_Connect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButton_Connect.setFont(font)
        self.pushButton_Connect.setObjectName("pushButton_Connect")
        self.verticalLayout_3.addWidget(self.pushButton_Connect)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonDown = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButtonDown.setFont(font)
        self.pushButtonDown.setObjectName("pushButtonDown")
        self.gridLayout.addWidget(self.pushButtonDown, 3, 1, 1, 1)
        self.pushButtonUp = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButtonUp.setFont(font)
        self.pushButtonUp.setObjectName("pushButtonUp")
        self.gridLayout.addWidget(self.pushButtonUp, 1, 1, 1, 1)
        self.pushButtonLeft = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButtonLeft.setFont(font)
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.gridLayout.addWidget(self.pushButtonLeft, 2, 0, 1, 1)
        self.pushButtonRight = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButtonRight.setFont(font)
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.gridLayout.addWidget(self.pushButtonRight, 2, 2, 1, 1)
        self.pushButtonSS = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButtonSS.setFont(font)
        self.pushButtonSS.setObjectName("pushButtonSS")
        self.gridLayout.addWidget(self.pushButtonSS, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 191, 211))
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 330, 181, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pushButton_follow = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButton_follow.setFont(font)
        self.pushButton_follow.setObjectName("pushButton_follow")
        self.verticalLayout_2.addWidget(self.pushButton_follow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelView.setText(_translate("MainWindow", "View"))
        self.pushButtonw.setText(_translate("MainWindow", "前进"))
        self.pushButton_stop.setText(_translate("MainWindow", "停止"))
        self.pushButtona.setText(_translate("MainWindow", "左转"))
        self.pushButtons.setText(_translate("MainWindow", "后退"))
        self.pushButtond.setText(_translate("MainWindow", "右转"))
        self.label_3.setText(_translate("MainWindow", "速度："))
        self.pushButton_Connect.setText(_translate("MainWindow", "开始连接"))
        self.pushButtonDown.setText(_translate("MainWindow", "下"))
        self.pushButtonUp.setText(_translate("MainWindow", "上"))
        self.pushButtonLeft.setText(_translate("MainWindow", "左"))
        self.pushButtonRight.setText(_translate("MainWindow", "右"))
        self.pushButtonSS.setText(_translate("MainWindow", "释放云台"))
        self.label.setText(_translate("MainWindow", "LOGO"))
        self.label_2.setText(_translate("MainWindow", "功能列表"))
        self.pushButton_follow.setText(_translate("MainWindow", "物体跟随"))

